# Setup
name:         Wroohtteeen!
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "zh_cn"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
